[package]
name = "walkingpad_protocol"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
btleplug = "0.9"
futures = "*"
tokio = { version = "*", features = ["macros", "rt-multi-thread"]}
uuid = "^0.8"

[dependencies]
bitflags = "^1.3"
strum = "0.24"
strum_macros = "0.24"
