[package]
name = "walkingpad_protocol"
version = "0.1.0"
edition = "2021"

[features]
std = ["dep:time", "measurements/std"]

[dependencies]
bitflags = "^1.3"
strum = "0.24"
strum_macros = "0.24"
impl_ops = "0.1"
time = { version = "0.3", features = ["std", "formatting"], optional = true }
measurements = "0.11"
